spring.datasource.url=jdbc:mysql://localhost:3306/db_granja?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.profiles.active=test

api.security.token.secret=Zeno Espig e o fundador da empresa Verduras Vale Das Cachoeiras Kiara e Flora sao uns amores
api.token.expiration=18000000

